services:
  crypto-volume-scanner:
    image: cvs
    container_name: cvs_api
    build: .
    ports: 
      - 8000:8000 
      - 6060:6060 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - cvs-postgres          
    networks:
      - cvs-network

  cvs-postgres:
    image: postgres:latest
    container_name: cvs_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - 5434:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - cvs-network

volumes:
  api:
  database_postgres: 

# Networks to be created to facilitate communication between containers
networks:
   cvs-network:
    driver: bridge